version: "3"

services:
  rails:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql
    depends_on:
      - "mysql"
    stdin_open: true
    tty: true
  mysql:
    image: "mysql:8"
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  data-volume:
